### ISSUE TITLE
Website is unusable on some lower spec hardware

### ISSUE THREAD

**Issue by star-buck** [Nitrux/nitrux-website-html5#7]
Please make the current website (I know this is an old repo, still putting this here) work without all that super-heavy Youtube Videos and Javascript madness.
It simply didnt ever finish initliazing loading here, and overall is a very discouraging experience and in stark contrast to the somewhat light-hearted and -weighed experience from nomad.
Thanks for taking care of this.

**Comment by UriHerrera** [comment]
Moved to: https://github.com/Nitrux/wordpress-sites-tracker/issues/1
